### ISSUE TITLE
[Servlet-003] : PDF documents are not rendering properly 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java#35]
This issue was originally raised via forum thread:
http://groupdocs.com/Community/forums/thread/16068/pdf-file-not-rendering-properly.aspx

PDF documents are not properly rendering in viewer when use html base engine is set to true "useHtmlBasedEngine : true" using GroupDocs.Viewer for Java 3.7.0.

**Comment by usmanazizgroupdocs** [comment]
This issue is fixed in [GroupDocs.Viewer-for-Java-App](https://forum.groupdocs.com/t/pdf-file-not-rendering-properly/2125/4).
