### ISSUE TITLE
[ModernUI:001] : Thumbnails/page navigation is not properly done

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java#49]
This issue was originally raised via forum thread:
http://www.groupdocs.com/Community/forums/thread/18307/performance-issue.aspx

Greetings,
Modern UI showcase project doesn't show thumbnails and doesn't perform page navigation (i:e http://localhost:8080/page/image?page=35&file=sample.pptx). There were no such issues in older version of the API (3.7.0). Please see, if you reproduce same issues at your end as well.
Thanks

**Comment by usmanazizgroupdocs** [comment]
This issue is fixed in [GroupDocs.Viewer-for-Java-App](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-App).
