### ISSUE TITLE
Update front ends for version 17.5.0

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java#57]
Update front ends for the latest version (17.5.0) of GroupDocs.Viewer for Java.
This enhancement is also requested in:
[https://forum.groupdocs.com/t/document-text-not-rendered-properly-inside-viewer/1970/45?u=usman.aziz](https://forum.groupdocs.com/t/document-text-not-rendered-properly-inside-viewer/1970/45?u=usman.aziz)

**Comment by AamirWaseem** [comment]
@usmanazizgroupdocs 
Updated with version 17.5.0, please verify and notify to customer.
