### ISSUE TITLE
Print PDF is not working aptly

### ISSUE THREAD

**Issue by mcqueide** [groupdocs-viewer/GroupDocs.Viewer-for-Java#68]
I made a test with branch master, and another test in the demo application, in both tests I could print but the document was unformatted.

**Comment by aspose-com-kb** [comment]
@mcqueide 

Please post your query along with the details like code and files etc. in [GroupDocs free support forum](https://forum.groupdocs.com/) so our support team can help you properly and timely.

**Comment by vladimir-litvinchik** [comment]
@mcqueide 

This issue has been fixed in the latest commit.
