### ISSUE TITLE
What is replacement for PageImpl constructor

### ISSUE THREAD

**Issue by securelyshare-shiva-kumar** [groupdocs-viewer/GroupDocs.Viewer-for-Java#69]
Project details:
Spring

I changed the Groupdocs viewer dependency to 21.2 and ran into compilation error in Utils.java class, applyWidthHeightFix method in this line of code.

```java
pages.set(n, new Page(page.getNumber(), page.isVisible(), (fixWidth == 0) ? lastFixWidth : fixWidth, (fixHeight == 0) ? lastFixHeight : fixHeight, page.getLines()));
```

In 21.2 version Page is an interface and default implementation PageImpl is deprecated what is the suitable replacement for this.

**Comment by liosha2007** [comment]
> 

Hello. 
You can still use PageImpl class, it will not be deleted. But in this way you will not have opportunity to create custom models for your own implementation of serialization. The recommended way is to use CacheableFactory. There are methods for creating new instances of models. 
For example: 
`CacheableFactory.getInstance().newPage(page.getNumber(), page.isVisible(), (fixWidth == 0) ? lastFixWidth : fixWidth, (fixHeight == 0) ? lastFixHeight : fixHeight, page.getLines()));`

More details can be found [in documentation](https://docs.groupdocs.com/viewer/java/how-to-use-custom-cache-implementation/)
