### ISSUE TITLE
CPU and Memory Usage Maxed

### ISSUE THREAD

**Issue by tomislavmedicaspose** [groupdocs-viewer/GroupDocs.Viewer-for-Java#76]
Steps to reproduce:
    - Open a PDF document with XFA artifacts in the viewer (viewer in HTML mode)

  Symptom:
   - If preloadPageCount = 0, loadDocumentDescription completes successfully and the document renders correctly.
   - If preloadPageCount > 0, loadDocumentDescription completes successfully, but loadDocumentPage creates a race condition 
 
   - When this condition occurs, we can see two threads being occupied in the VM, and both become stuck in the RUNNING state, with no ability to finish or exit (which prevents the release of the CPU resources being used).

**Comment by vladimir-litvinchik** [comment]
@tomislavmedicaspose 

Thank you for reporting this issue. We'll try reproducing it on our side and update you here.

**Comment by liosha2007** [comment]
@tomislavmedicaspose , @vladimir-litvinchik I reproduced the problem and working on solving it.

**Comment by liosha2007** [comment]
@tomislavmedicaspose , @vladimir-litvinchik I have solved the problem - [commit](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java/commit/00ace5ead0e00793e9b293c455c4d4cc887317f7).
Now threads are free after doing all the work and are alive until Java thread pool decides to free them.
